### ISSUE TITLE
Support Complex SearchExpression

### ISSUE THREAD

**Issue by ximex** [ximex/ris-bka#6]
This doesn't work until a bug in the jsonix lib get fixed
highsource/jsonix#68
highsource/jsonix-support#3

until this get fixed, only `PhraseSearchExpression` is supported

**Comment by highsource** [comment]
This must be fixed in Jsonix Schema Compiler 2.3.3 and Jsonix 2.2.1. `xsi:type` is now [officially supported](https://github.com/highsource/jsonix/wiki/xsi%3Atype-Support).

Please also see [support project](https://github.com/highsource/jsonix-support/tree/master/r/ris-bka). I've reworked the project structure a bit, now `package.json` includes schema generation which will be executed on `npm install`.

Generation results in two modules `OGD_1_3` (containing `OGD` and `OGD_DocumentResponse` mappings) and `SOAP_1_2` (containing `SOAP_Envelope` mapping).

See the [test case](https://github.com/highsource/jsonix-support/blob/master/r/ris-bka/tests/OGD.js) for usage example.

``` javascript
var Jsonix = require('jsonix').Jsonix;
var OGD = require('../mappings/OGD_1_3').OGD;
var OGD_DocumentResponse = require('../mappings/OGD_1_3').OGD_DocumentResponse;
var mappings = [OGD, OGD_DocumentResponse];
```

**Comment by ximex** [comment]
the simple `PhraseSearchExpression` works. I have to test the complexe SearchExpressions too.

Is it correct that i only have to set the `TYPE_NAME` at `suchworte, titel, index`? `kundmachungsorgan, kundmachungsorgannummer` works without too.

**Comment by highsource** [comment]
Yes. You need TYPE_NAME iff you want to output a type different than the declared. (In your case - a subtype.) In this case Jsonix will generate an additional xsi:type attribute.

**Comment by ximex** [comment]
@highsource
ok all looks great except the `NotSearchExpression`

``` javascript
{
  "TYPE_NAME": "OGD_Request.AndSearchExpression",
  "expressions": {
    "TYPE_NAME": "OGD_Request.ArrayOfSearchExpression",
    "searchExpression": [
      {
        "TYPE_NAME": "OGD_Request.NotSearchExpression",
        "expressions": {
          "TYPE_NAME": "OGD_Request.PhraseSearchExpression",
          "value": "straße*"
        }
      },
      {
        "TYPE_NAME": "OGD_Request.PhraseSearchExpression",
        "value": "kfz"
      }
    ]
  }
}
```

from the marschalling i got:

``` xml
<Suchworte xsi:type="AndSearchExpression">
  <Expressions>
    <SearchExpression xsi:type="NotSearchExpression"/>
    <SearchExpression xsi:type="PhraseSearchExpression">
      <Value>kfz</Value>
    </SearchExpression>
  </Expressions>
</Suchworte>
```

it should look like:

``` xml
<Suchworte xsi:type="AndSearchExpression">
  <Expressions>
    <SearchExpression xsi:type="NotSearchExpression">
      <Expression xsi:type="PhraseSearchExpression">
        <Value>straße*</Value>
      </Expression>
    </SearchExpression>
    <SearchExpression xsi:type="PhraseSearchExpression">
      <Value>kfz</Value>
    </SearchExpression>
  </Expressions>
</Suchworte>
```

**Comment by ximex** [comment]
Ok i found the mistake. It should be `Expression` and not `Expressions`. For some reason i don't got a response with this request. maybe this is an other bug

**Comment by ximex** [comment]
implemented
NotSearchExpression bug see here: #15
